# Generated by Django 5.2.3 on 2025-07-10 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(help_text='Name of the project.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='optional longer description')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to archive a project without having to delete it')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='which employees can book time on this project.', related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'ordering': ['code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.project'),
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together={('user', 'project', 'date')},
        ),
    ]
