# Generated by Django 5.2.3 on 2025-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_project_alter_timeentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='submitted',
            field=models.BooleanField(default=False, help_text='Whether this entry has been submitted'),
        ),
    ]
