# Generated by Django 5.2.3 on 2025-08-06 10:55

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0004_leavetype_user_manager_leaverequest_leaveentitlement"),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return

        superuser = User.objects.create_superuser(
            username="jaked",
            email="jaked.dev10@gmail.com",
            password="Htcrajsed90",
            last_login=timezone.now(),
        )
        superuser.save()

    operations = [migrations.RunPython(create_superuser)]
